[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/users/me"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
NPM_CONFIG_PRODUCTION = "false"
