[build]
builder = "DOCKERFILE"

[deploy]
preDeployCommand = ["/app/backend/node_modules/.bin/prisma migrate deploy --schema /app/backend/prisma/schema.prisma"]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
NPM_CONFIG_PRODUCTION = "false"
